# Configuration des surcharges de dépendances
overrides:
  "hono": "4.12.25"

# Autorisations pour l'exécution des scripts de build (postinstall, etc.)
allowBuilds:
  '@prisma/engines': true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
